ors:
  engine:
    graphs_root_path: /home/ors/graphs

    profile_default:
      build:
        source_file: /home/ors/files/map-data.osm.pbf
    profiles:
      driving-car:
        enabled: true
      cycling-regular:
        enabled: false
      foot-walking:
        enabled: true
  endpoints:
    routing:
      enabled: true
    isochrones:
      enabled: true
    matrix:
      enabled: true
      maximum_routes: 10000
      maximum_visited_nodes: 10000000
      maximum_visited_nodes_matrix: 100000000
